version: "3"
services:
  db:
    image: mysql
    container_name: MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - gesprendercoreframework
  php:
    build: ./docker/.
    container_name: PHP8.2
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      - gesprendercoreframework
  phpmyadmin:
    image: phpmyadmin
    container_name: PHPMyAdmin
    restart: always
    ports:
      - 3001:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=MySQL
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - gesprendercoreframework

networks:
  gesprendercoreframework:
    name: gesprendercoreframework
    driver: bridge